// Generated by CoffeeScript 1.4.0

/* Configuration file - Set your MySQL info here
*/


(function() {

  exports.HOSTNAME = process.env.HOSTNAME || 'localhost';

  exports.PORT = process.env.PORT || '3000';

  exports.DB_HOSTNAME = process.env.DB_HOSTNAME || 'localhost';

  exports.DB_PORT = process.env.DB_PORT || '3306';

  exports.DB_USERNAME = process.env.DB_USERNAME || '';

  exports.DB_PASSWORD = process.env.DB_PASSWORD || '';

  exports.DB_DATABASE = process.env.DB_DATABASE || '';

}).call(this);
