// Generated by CoffeeScript 1.4.0

/* Tests for Database /lib/db.coffee
*/


(function() {
  var Db, cfg, db, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  Db = (require('../lib/db.js')).Db;

  /* Initialize DB
  */


  db = new Db(cfg);

  describe('Connect to MySQL server', function() {
    return it('Should return a basic query', function(done) {
      return db.test(function(err, callback) {
        var row, sampleRow;
        sampleRow = JSON.stringify({
          '1': 1
        });
        row = callback[0];
        should.not.exist(err);
        JSON.stringify(row).should.equal(sampleRow);
        return done();
      });
    });
  });

  describe('Get a single transaction', function() {
    it('Should return a known transaction', function(done) {
      var sampleRow, sampleTransactionID;
      sampleTransactionID = 1;
      sampleRow = {
        transaction_id: 1,
        transaction_payment_type: "visa",
        transaction_void: 0,
        transaction_total: 4.90
      };
      return db.getTransaction(sampleTransactionID, function(err, callback) {
        var row;
        should.not.exist(err);
        row = callback[0];
        row.transaction_id.should.equal(sampleRow.transaction_id);
        row.transaction_payment_type.should.equal(sampleRow.transaction_payment_type);
        row.transaction_void.should.equal(sampleRow.transaction_void);
        row.transaction_total.should.equal(sampleRow.transaction_total);
        return done();
      });
    });
    return it('Should error out if no id is provided', function(done) {
      var sampleTransactionID;
      sampleTransactionID = null;
      return db.getTransaction(sampleTransactionID, function(err, callback) {
        should.exist.err;
        err.should.equal("Error: No id defined");
        should.not.exist(callback);
        return done();
      });
    });
  });

  describe('Get a group of transaction entries by date', function() {
    it('Should return a set of transaction entries given a start and end date', function(done) {
      var sampleEndDate, sampleGiftCards, sampleRow, sampleStartDate, sampleVoided;
      sampleStartDate = "2012-06-01 00:00:01";
      sampleEndDate = "2012-09-01 00:00:01";
      sampleGiftCards = false;
      sampleVoided = true;
      sampleRow = {
        transaction_id: 1,
        transaction_payment_type: "visa",
        transaction_void: 0,
        transaction_total: 4.90
      };
      return db.getTaxByQuarter(sampleStartDate, sampleEndDate, sampleGiftCards, sampleVoided, function(err, callback) {
        var rows;
        should.not.exist(err);
        rows = callback;
        rows[0].type.should.equal('service');
        rows[0].total.should.equal(154196);
        rows[1].type.should.equal('product');
        rows[1].total.should.equal(18249.45);
        return done();
      });
    });
    it('Should error out if no start date is provided', function(done) {
      var sampleEndDate, sampleGiftCards, sampleStartDate, sampleVoided;
      sampleStartDate = null;
      sampleEndDate = "blah";
      sampleGiftCards = false;
      sampleVoided = false;
      return db.getTaxByQuarter(sampleStartDate, sampleEndDate, sampleGiftCards, sampleVoided, function(err, callback) {
        should.exist.err;
        err.should.equal("Error: No start date defined");
        should.not.exist(callback);
        return done();
      });
    });
    return it('Should error out if no end date is provided', function(done) {
      var sampleEndDate, sampleGiftCards, sampleStartDate, sampleVoided;
      sampleStartDate = "blah";
      sampleEndDate = null;
      sampleGiftCards = false;
      sampleVoided = false;
      return db.getTaxByQuarter(sampleStartDate, sampleEndDate, sampleGiftCards, sampleVoided, function(err, callback) {
        should.exist.err;
        err.should.equal("Error: No end date defined");
        should.not.exist(callback);
        return done();
      });
    });
  });

}).call(this);
