// Generated by CoffeeScript 1.4.0

/* Tests for Database /lib/db.coffee
*/


(function() {
  var Db, cfg, db, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  Db = (require('../lib/db.js')).Db;

  /* Initialize DB
  */


  db = new Db(cfg);

  describe('Connect to MySQL server', function() {
    return it('Should return a basic query', function(done) {
      return db.test(function(err, callback) {
        var sampleRow;
        sampleRow = JSON.stringify({
          '1': 1
        });
        should.not.exist(err);
        JSON.stringify(callback[0]).should.equal(sampleRow);
        return done();
      });
    });
  });

}).call(this);
